### ISSUE TITLE
ActionBar Back button causes FC after merging #104

### ISSUE THREAD

**Issue by zdunex25** [afollestad/polar-dashboard#107]
After merging #104 code fix then you go to Icons > More (then tap on Back button in actionbar) this happens:

```Gradle
04-26 16:08:16.377 31364-31364/com.afollestad.polar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afollestad.polar, PID: 31364
    java.lang.RuntimeException: Unable to resume activity {com.afollestad.polar/com.afollestad.polar.ui.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
        at android.os.Handler.dispatchMessage(Handler.java)
        at android.os.Looper.loop(Looper.java)
        at android.app.ActivityThread.main(ActivityThread.java)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java)
        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java)
        at com.afollestad.polar.config.Config.prefs(Config.java:62)
        at com.afollestad.polar.config.Config.darkTheme(Config.java:79)
        at com.afollestad.polar.config.Config.darkTheme(Config.java:73)
        at com.afollestad.polar.ui.base.BaseThemedActivity.darkTheme(BaseThemedActivity.java:140)
        at com.afollestad.polar.ui.base.BaseThemedActivity.onResume(BaseThemedActivity.java:99)
        at com.afollestad.polar.ui.base.BaseDonateActivity.onResume(BaseDonateActivity.java:27)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java)
        at android.app.Activity.performResume(Activity.java)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
        at android.os.Handler.dispatchMessage(Handler.java) 
        at android.os.Looper.loop(Looper.java) 
        at android.app.ActivityThread.main(ActivityThread.java) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by afollestad** [comment]
Let me know if what I just pushed doesn't work.

**Comment by afollestad** [comment]
Pushed more code to help

**Comment by zdunex25** [comment]
No more FC :) thanks.
