### ISSUE TITLE
Set HomePage FAB to open apply fragment.

### ISSUE THREAD

**Issue by a-random-package** [afollestad/polar-dashboard#126]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `0.8.6.1`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Note4`

I would just like to change the behavior of the FAB on the Homepage fragment to open the Apply fragment. I tried what I thought would work:

HomeFragment.java

```java
@OnClick(R.id.fab)
    public void onTapReview() {
        Intent intent = new Intent(getActivity(), ApplyFragment.class);
        startActivity(intent);
    }
```

But it didn't How would you recommend I go about it? 

```Gradle
FATAL EXCEPTION: main
Process: com.arandompackage.banded, PID: 464
                                                                       android.content.ActivityNotFoundException: Unable to find explicit activity class {com.arandompackage.banded/com.arandompackage.banded.fragments.ApplyFragment}; have you declared this activity in your AndroidManifest.xml?
                                                                           at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1630)
                                                                           at android.app.Activity.startActivityForResult(Activity.java:4549)
                                                                           at android.app.Activity.startActivityFromFragment(Activity.java:4535)
                                                                           at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:6609)
                                                                           at android.app.Fragment.startActivity(Fragment.java:1092)
                                                                           at android.app.Fragment.startActivity(Fragment.java:1071)
                                                                           at com.arandompackage.banded.fragments.HomeFragment.onTapReview(HomeFragment.java:49)
                                                                           at com.arandompackage.banded.fragments.HomeFragment$$ViewBinder$InnerUnbinder$1.doClick(HomeFragment$$ViewBinder.java:33)
                                                                           at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                           at android.view.View.performClick(View.java:5198)
                                                                           at android.view.View$PerformClick.run(View.java:21147)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

It isn't assignable to an activity in the Manifest. I tried that already.

**Comment by afollestad** [comment]
You're trying to start the `ApplyFragment` as an `Activity`. `ApplyFragment` is a `Fragment`, not an `Activity`.

**Comment by afollestad** [comment]
You're trying to start the `ApplyFragment` as an `Activity`. `ApplyFragment` is a `Fragment`, not an `Activity`. 

`ApplyFragment` is inside of the `ViewPager` that's in the main layout of `MainActivity`.
