### ISSUE TITLE
App crashes on KitKat with the latest polar update 1.60

### ISSUE THREAD

**Issue by mddanishansari** [afollestad/polar-dashboard#127]
With the latest polar update there's some issue. The app crashes on KitKat. It doesn't even starts. 

I got the logs I got from the users through developer console. I viewed it and I think it's the issues **selecter_tab.xml** file

The file was not there in my previous versions of polar. But it is now.

**Here is the log:**

```Gradle
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.md.emenox/com.afollestad.polar.ui.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/selector_tabs.xml from drawable resource ID #0x7f020087
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2507)
	at android.app.ActivityThread.access$900(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5692)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/selector_tabs.xml from drawable resource ID #0x7f020087
	at android.content.res.Resources.loadDrawable(Resources.java:3368)
	at android.content.res.Resources.getDrawable(Resources.java:1864)
	at android.content.res.XResources.getDrawable(XResources.java:521)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
	at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1510)
	at android.support.design.widget.TabLayout.createTabView(TabLayout.java:926)
	at android.support.design.widget.TabLayout.newTab(TabLayout.java:563)
	at com.afollestad.polar.ui.MainActivity.addTab(MainActivity.java:465)
	at com.afollestad.polar.ui.MainActivity.setupTabs(MainActivity.java:401)
	at com.afollestad.polar.ui.MainActivity.onCreate(MainActivity.java:128)
	at android.app.Activity.performCreate(Activity.java:5541)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
	... 12 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/selector_tabs_selected.xml from drawable resource ID #0x7f020088
	at android.content.res.Resources.loadDrawable(Resources.java:3368)
	at android.content.res.Resources.getDrawable(Resources.java:1864)
	at android.content.res.XResources.getDrawable(XResources.java:521)
	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:176)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:990)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
	at android.content.res.Resources.loadDrawable(Resources.java:3364)
	... 26 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.content.res.XResources$XTypedArray.getColor(XResources.java:889)
	at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:990)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
	at android.content.res.Resources.loadDrawable(Resources.java:3364)
	... 32 more
```

I recommend developers to check the sample app on different KitKat device and then come to some conclusion.

**Comment by zavukodlak** [comment]
I am having the same issue. It seems like its happening on all android versions below Lollipop.

**Comment by afollestad** [comment]
@mddanishansari @zavukodlak fixed in the latest commit
