### ISSUE TITLE
Polar - Dashboard crashes when viewing Icons on Huawei

### ISSUE THREAD

**Issue by Agronaut022** [afollestad/polar-dashboard#157]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: 1.9
 - Device OS version: 6.0
 - Device Manufacturer: Huawei
 - Device Name: P8 lite

Everytime i try to view all icons that i have included in my App it always crashes at exactly the 41 icon.
This also seems to happen on a friends phone but i wasnt able to get a stack trace of His Phone
His Phone is Moto g 2 Generation.

Stacktrace:

```Gradle
 java.lang.NoSuchFieldException: No field mCursorDrawable in class Lhuawei/com/android/internal/widget/HwEditor; (declaration of 'huawei.com.android.internal.widget.HwEditor' appears in /system/framework/hwEmui.jar)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at com.afollestad.polar.util.TintUtils.setCursorTint(TintUtils.java:123)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at com.afollestad.polar.util.TintUtils.themeSearchView(TintUtils.java:75)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at com.afollestad.polar.fragments.IconsFragment.onCreateOptionsMenu(IconsFragment.java:191)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2314)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2036)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at android.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:265)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at android.app.Activity.onCreatePanelMenu(Activity.java:2947)
08-26 15:55:19.651 16600-16600/com.puppy.childish W/System.err:     at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:362)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:696)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:628)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.os.Handler.handleCallback(Handler.java:743)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.os.Looper.loop(Looper.java:150)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5546)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
08-26 15:55:19.652 16600-16600/com.puppy.childish W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```
 
###### Reproduction Steps

1.  Have More than 40 Icons
2. Try to view All icons
3. Scroll Down

###### Expected Result

Shows Icons

###### Actual Result

Crashes

**Comment by Agronaut022** [comment]
I just made a  Typing error in code sorry for creating a useless issue
