### ISSUE TITLE
Loading kustom presets fail

### ISSUE THREAD

**Issue by marcogenovese** [afollestad/polar-dashboard#162]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Polar Dashboard.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Polar Dashboard version: `1.9`
 - Device OS version: `7.0`
 - Device Manufacturer: `huawei`
 - Device Name: `P9`

Bug trace:

I/art: Do full code cache collection, code=502KB, data=447KB
I/art: After code cache collection, code=446KB, data=370KB
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/sforkwgt.genoma.kustom/cache/KustomPreviews/Google_1_4x1.kwgt (No such file or directory)
W/System.err: at java.io.FileOutputStream.open(Native Method)
W/System.err: at java.io.FileOutputStream.(FileOutputStream.java:221)
W/System.err: at java.io.FileOutputStream.(FileOutputStream.java:169)
W/System.err: at sforkwgt.genoma.kustom.kustom.KustomUtil$1.run(KustomUtil.java:113)
W/System.err: at java.lang.Thread.run(Thread.java:776)
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void java.io.Closeable.close()' on a null object reference
W/System.err: at sforkwgt.genoma.kustom.util.Utils.closeQuietly(Utils.java:20)
W/System.err: at sforkwgt.genoma.kustom.kustom.KustomUtil$1.run(KustomUtil.java:177)
W/System.err: at java.lang.Thread.run(Thread.java:776)
 
###### Reproduction Steps

1. Open dashboard 
2. Tap on "kustom" tab

###### Expected Result

Kustom items (widgtes or wallpapers depends which tab)

###### Actual Result

Sometimes No items

**Comment by marcogenovese** [comment]
@frmz

**Comment by marcogenovese** [comment]
setting minifyEnabled to false fix the issue but could be a better solution to keep linked classes from Progurad

**Comment by marcogenovese** [comment]
After one day I have to reopen this issue. Setting minifyEnabled to false lowered the frequency of the issue but doesn't fix at all. In addition to the usual
<java.lang.NullPointerException: Attempt to invoke interface method 'void java.io.Closeable.close()' on a null object reference>
today I get the error:
<file too short to be a zip file: 0>
So the issue is still there.
@frmz
