### ISSUE TITLE
Inquiry crash might still exist

### ISSUE THREAD

**Issue by FrancisCan** [afollestad/polar-dashboard#39]
There is a crash if you open and close the app while apps list is preparing to load yet
```Gradle
FATAL EXCEPTION: Thread-3424
Process: com.afollestad.polar, PID: 9451
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver
    android.content.Context.getContentResolver()' on a null object reference
    at com.afollestad.inquiry.Query.run(Query.java:200)
    at com.afollestad.inquiry.Query$2.run(Query.java:249)
    at java.lang.Thread.run(Thread.java:818)
```

and also a long loop errors regarding these 3 fonts: 
```
E/Minikin: addFont failed to create font /system/fonts/NanumGothic.ttf
E/Minikin: addFont failed to create font /system/fonts/DroidSansFallback.ttf
E/Minikin: addFont failed to create font /system/fonts/MTLmr3m.ttf
```

**Comment by afollestad** [comment]
The first crash should already be fixed with the newer code, but I'll double check.

The second are not related to Polar in any way.

**Comment by afollestad** [comment]
This should already be fixed in the newer code as long as you had upgraded correctly.
