### ISSUE TITLE
Crash When Opening App From Drawable View in Nova

### ISSUE THREAD

**Issue by danielhickman** [afollestad/polar-dashboard#65]
Trigger:
![screenshot_2016-02-17-21-08-11](https://cloud.githubusercontent.com/assets/5341898/13134381/9d0ec94a-d5ba-11e5-86d8-5fb572f9d6bb.png)

Crash: (so helpful, I know)
![screenshot_2016-02-17-21-05-19](https://cloud.githubusercontent.com/assets/5341898/13134361/5302296e-d5ba-11e5-83c1-14cf8ba54c92.png)

**Comment by danielhickman** [comment]
Filed a crash report on Gaufer with the title name.

**Comment by afollestad** [comment]
I'm surprised I didn't catch this before, I'll have it fixed when I'm done with work (or maybe sooner). Thanks

**Comment by afollestad** [comment]
```Gradle
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wellingtomworks.gaufrer/com.wellingtomworks.gaufrer.ui.IconPickerActivity}: java.lang.RuntimeException: Unable to bind views for com.wellingtomworks.gaufrer.ui.IconPickerActivity
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.access$800(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.RuntimeException: Unable to bind views for com.wellingtomworks.gaufrer.ui.IconPickerActivity
	at butterknife.ButterKnife.bind(ButterKnife.java:322)
	at butterknife.ButterKnife.bind(ButterKnife.java:237)
	at com.wellingtomworks.gaufrer.ui.IconPickerActivity.onCreate(IconPickerActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:6010)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
	... 10 more
Caused by: java.lang.IllegalStateException: Required view 'toolbar' with ID 2131624058 for field 'toolbar' was not found. If this view is optional add '@Nullable' annotation.
	at butterknife.ButterKnife$Finder.findRequiredView(ButterKnife.java:140)
	at com.wellingtomworks.gaufrer.ui.IconPickerActivity$$ViewBinder.bind(IconPickerActivity$$ViewBinder.java:11)
	at com.wellingtomworks.gaufrer.ui.IconPickerActivity$$ViewBinder.bind(IconPickerActivity$$ViewBinder.java:8)
	at butterknife.ButterKnife.bind(ButterKnife.java:319)
	... 15 more
```

**Comment by afollestad** [comment]
https://github.com/afollestad/polar-dashboard/releases/tag/1.3.0
