### ISSUE TITLE
Application crash on back press

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/polar-dashboard#66]
The latest Application's source crashes when pressing the back button.
Reason:

```
FATAL EXCEPTION: main
                                                                      Process: com.afollestad.polar, PID: 10308
                                                                      java.lang.RuntimeException: Unable to pause activity {com.afollestad.polar/com.afollestad.polar.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
                                                                          at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
                                                                          at android.app.ActivityThread.-wrap13(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
                                                                          at com.afollestad.polar.adapters.ZooperAdapter.recycle(ZooperAdapter.java:140)
                                                                          at com.afollestad.polar.fragments.ZooperFragment.onPause(ZooperFragment.java:155)
                                                                          at android.app.Fragment.performPause(Fragment.java:2379)
                                                                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1019)
                                                                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                                          at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
                                                                          at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:1967)
                                                                          at android.app.FragmentController.dispatchPause(FragmentController.java:185)
                                                                          at android.app.Activity.performPause(Activity.java:6361)
                                                                          at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
                                                                          at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340) 
                                                                          at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315) 
                                                                          at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by afollestad** [comment]
https://github.com/afollestad/polar-dashboard/releases/tag/1.3.0
