### ISSUE TITLE
'No apps' & crash in Icon Request section in 1.3.2. 

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#74]
**EDIT** I think this is on my end, the sample is fine, but I can't figure it out. 

I've both tried this with an update via the PUT tool and a fresh setup from the latest source. The app is showing 'No Apps' on the request screen. (It'll crash when tapping the select all button, but I guess that's just an effect of the no apps). 

I stripped back the changes from the app filter I made, but it didn't do anything. Not sure if it is something with my app filter, but I see nothing different. 

![2016-03-03 09 43 09](https://cloud.githubusercontent.com/assets/5175919/13490442/7e900c16-e124-11e5-8c1f-40fb2583d079.png)

Just in case, crash log:

 ```Gradle
03-03 09:43:45.218  14133-14133/com.ryanmkelly.me.tendere E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ryanmkelly.me.tendere, PID: 14133
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
            at java.util.ArrayList.addAll(ArrayList.java:188)
            at com.afollestad.iconrequest.IconRequest.selectAllApps(IconRequest.java:312)
            at com.ryanmkelly.me.tendere.fragments.RequestsFragment.onOptionsItemSelected(RequestsFragment.java:172)
            at android.app.Fragment.performOptionsItemSelected(Fragment.java:2159)
            at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:1988)
            at android.app.Activity.onMenuItemSelected(Activity.java:2888)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:404)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:167)
            at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
            at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
            at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
            at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:169)
            at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
            at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
            at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
            at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
            at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
            at android.view.View.performClick(View.java:4789)
            at android.view.View$PerformClick.run(View.java:19881)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5294)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by TWellington** [comment]
Thanks for the log! Aidan can take a look when he's got time. 

Here's a link to another stack trace: http://pastebin.com/TFk2s1qG

**Comment by afollestad** [comment]
Thanks guys

**Comment by Jamz442** [comment]
I'm using 1.3.2 right now and I haven't got this issue. However I did have it previously. Aidan told me there were some typos in the appfilter.xml that was causing it.

**Comment by ryanmkelly** [comment]
@Jamz442 I thought that might have been the case, after checking and running through a xml checker, nothing came up, I reverted to an xml which was/is working fine with earlier versions and it had the same issue.

**Comment by ryanmkelly** [comment]
Just noticed I'm getting a rendering issue in the fragment_requesticons.xml, I don't believe it's causing the issue. 

Here is a stack: 

`android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0202c2
	at android.content.res.Resources.getResourceName(Resources.java:2235)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2602)
	at android.content.res.Resources.loadDrawable(Resources.java:2540)
	at android.content.res.Resources.getDrawable(Resources.java:806)
	at android.content.Context.getDrawable(Context.java:458)
	at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:180)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:173)
	at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:46)
	at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:65)
	at android.support.design.widget.VisibilityAwareImageButton.<init>(VisibilityAwareImageButton.java:37)
	at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:109)
	at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:105)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:437)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:154)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:93)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:190)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:247)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:171)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:835)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:223)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:511)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:499)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:499)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:611)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:365)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:630)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:643)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:580)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
`

**Comment by afollestad** [comment]
The first problem should be gone now (if there's still a problem, it should give you an error message rather than crashing).

That second log isn't from Polar, it's from Android Studio.

**Comment by a-random-package** [comment]
I'm getting this issue on the latest source. Did anyone ever figure out the fix?

**Comment by TWellington** [comment]
We've always had an issue with CyanogenMod, and I'm not sure why. It takes
30 seconds to 2 minutes to load, but we've never been able to find the
reason for it

**Comment by a-random-package** [comment]
It's happening on a Nexus 6P fully stock Android 7.

**Comment by TWellington** [comment]
Interesting. @afollestad got time to check it out?

**Comment by afollestad** [comment]
I work 8 to 6 so I probably won't have much time soon

**Comment by a-random-package** [comment]
That's cool. I do contribute a little bit to your RM server so it would be nice to use it too.
