### ISSUE TITLE
Tapping on icons preview causes a FC

### ISSUE THREAD

**Issue by Bones28** [afollestad/polar-dashboard#81]
Upon tapping on any of the icons on the icons section I get a force close. Though when i tap on them within a sub-category (i.e 'new') it's fine and doesn't force close. Maybe the error below can help.

> 03-06 19:57:15.612 2892-2892/com.skykonig.acornicons E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.skykonig.acornicons, PID: 2892
                                                                       java.lang.ClassCastException: com.skykonig.acornicons.ui.MainActivity cannot be cast to com.skykonig.acornicons.ui.base.ISelectionMode
                                                                           at com.skykonig.acornicons.fragments.IconsFragment.selectItem(IconsFragment.java:85)
                                                                           at com.skykonig.acornicons.fragments.IconsFragment$3.onClick(IconsFragment.java:182)
                                                                           at com.skykonig.acornicons.adapters.IconAdapter.onClick(IconAdapter.java:45)
                                                                           at android.view.View.performClick(View.java:5198)
                                                                           at android.view.View$PerformClick.run(View.java:21147)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by afollestad** [comment]
Fixed
