### ISSUE TITLE
ServiceConnection Leak from billing processor.

### ISSUE THREAD

**Issue by ryanmkelly** [afollestad/polar-dashboard#84]
No crashes or anything, but getting this when the app starts. 

```javascript
03-07 08:00:48.447    3294-3294/com.sixtyfourthirtytwo.redux E/ActivityThread﹕ Activity com.sixtyfourthirtytwo.redux.ui.MainActivity has leaked ServiceConnection com.anjlab.android.iab.v3.BillingProcessor$1@75a7727 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.sixtyfourthirtytwo.redux.ui.MainActivity has leaked ServiceConnection com.anjlab.android.iab.v3.BillingProcessor$1@75a7727 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1092)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:986)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1303)
            at android.app.ContextImpl.bindService(ContextImpl.java:1286)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
            at com.anjlab.android.iab.v3.BillingProcessor.bindPlayServices(BillingProcessor.java:116)
            at com.anjlab.android.iab.v3.BillingProcessor.<init>(BillingProcessor.java:109)
            at com.anjlab.android.iab.v3.BillingProcessor.<init>(BillingProcessor.java:98)
            at com.sixtyfourthirtytwo.redux.ui.base.BaseDonateActivity.onCreate(BaseDonateActivity.java:26)
            at com.sixtyfourthirtytwo.redux.ui.MainActivity.onCreate(MainActivity.java:108)
            at android.app.Activity.performCreate(Activity.java:6251)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by afollestad** [comment]
Code I just pushed should hopefully help, but this is most likely an issue with the library being used for In-App Purchases.
